# Generated by Django 6.0.5 on 2026-06-13 14:02

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('payment_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('failed', 'Ошибка'), ('completed', 'Завершено'), ('pending', 'В ожидании'), ('request_settled', 'Запрос завершен')], default='pending', max_length=100)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Перевод'), ('receive', 'Получение'), ('withdraw', 'Снятие'), ('replenishment', 'Пополнение'), ('none', 'Нет')], default='none', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=16, prefix='3222', unique=True)),
                ('cvc', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=3, max_length=3, prefix='')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type_credit_card', models.CharField(default='visa')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='account.account')),
            ],
            options={
                'verbose_name': 'Credi Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'CreditCard',
            },
        ),
    ]
