# Generated by Django 6.0.5 on 2026-06-13 14:02

import phonenumber_field.modelfields
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=13, max_length=30, prefix='', unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('accountID', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=14, prefix='DIDI', unique=True)),
                ('account_status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=40, region='UA')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'KYC',
            },
        ),
    ]
